// lib/businessTypeIcons.ts
// Diccionario: tipo de negocio → icono (emoji 3D / estilo sidebar)

export const BUSINESS_TYPE_ICONS: Record<string, string> = {
  supermercado: "🛒",
  hipermercado: "🏬",
  ultramarinos: "🥫",
  "tienda gourmet": "🧀",
  carnicería: "🥩",
  pescadería: "🐟",
  "panadería-pastelería": "🥐",
  frutería: "🍎",
  bodega: "🍷",
  delicatessen: "🍇",
  bar: "🍺",
  cafetería: "☕",
  restaurante: "🍽️",
  "food truck": "🚚",
  catering: "🥗",
  heladería: "🍦",
  "consulta médica": "🩺",
  dentista: "🦷",
  ortodoncia: "😁",
  fisioterapia: "🧘‍♂️",
  podología: "🦶",
  óptica: "👓",
  audiología: "👂",
  psicología: "🧠",
  psiquiatría: "💊",
  "nutrición-dietética": "🥦",
  rehabilitación: "🦿",
  "spa-balneario": "💧",
  yoga: "🧘‍♀️",
  pilates: "🧍‍♀️",
  "medicina estética": "💉",
  peluquería: "💇‍♀️",
  barbería: "💈",
  "centro de estética": "💅",
  "salón de uñas": "💅",
  "depilación láser": "🔦",
  microblading: "👁️",
  solárium: "🌞",
  tatuajes: "🖋️",
  piercing: "💎",
  "clínica veterinaria": "🐾",
  "hospital veterinario": "🏥",
  "peluquería canina": "🐶",
  "tienda de mascotas": "🐕",
  adiestramiento: "🎾",
  "guardería-residencia": "🏡",
  acuariofilia: "🐠",
  "reformas integrales": "🏗️",
  constructora: "🚧",
  ferretería: "🔩",
  carpintería: "🪚",
  cerrajería: "🔑",
  fontanería: "🚰",
  electricidad: "💡",
  "climatización-A/C": "❄️",
  calefacción: "🔥",
  "energías renovables": "🌞",
  cristalería: "🪟",
  pintura: "🎨",
  albañilería: "🧱",
  "suelos-parquet": "🪵",
  "toldos-persianas": "🏘️",
  domótica: "🏠",
  "control de plagas": "🐜",
  "tienda de ropa": "👗",
  boutique: "👜",
  outlet: "💸",
  calzado: "👟",
  deportes: "⚽",
  joyería: "💍",
  relojería: "⌚",
  "bolsos-complementos": "👜",
  mercería: "🧵",
  lencería: "👙",
  juguetería: "🧸",
  librería: "📚",
  papelería: "📎",
  "imprenta-copistería": "🖨️",
  "música-instrumentos": "🎸",
  "cómics-juegos": "🎲",
  "informática (retail)": "💻",
  "electrónica-telefonía (retail)": "📱",
  "bufete de abogados": "⚖️",
  procurador: "📜",
  notaría: "✒️",
  "gestoría-asesoría fiscal": "🧾",
  consultoría: "💼",
  "RR. HH.-laboral": "👥",
  "protección de datos-compliance": "🔒",
  "agencia de marketing": "📈",
  "diseño gráfico-branding": "🎨",
  arquitectura: "🏛️",
  ingeniería: "🧰",
  coworking: "🏢",
  "traducción-interpretación": "🗣️",
  auditoría: "📊",
  "call center-BPO": "🎧",
  "banco-sucursal": "🏦",
  "cooperativa de crédito": "💶",
  "correduría de seguros": "🛡️",
};

// Helper opcional (para buscar con fallback)
export function getBusinessIcon(type: string): string {
  if (!type) return "🏠";
  const key = type.trim().toLowerCase();
  return BUSINESS_TYPE_ICONS[key] ?? "🏠";
}
