// lib/businessTypeIcons.ts
// Diccionario: tipo de negocio (Type.name) → icono (emoji)

export const BUSINESS_TYPE_ICONS: Record<string, string> = {
  "itv-inspección": "🚗",
  "rr. hh.-laboral": "👥",
  "academia de baile": "💃",
  acuariofilia: "🐠",
  adiestramiento: "🎾",
  "administración de fincas": "🏢",
  "agencia de marketing": "📈",
  "agencia de viajes": "🧳",
  albañilería: "🧱",
  albergue: "🛏️",
  "alquiler de coches": "🚘",
  "alquiler de material para eventos": "🎪",
  "apartamento turístico": "🏙️",
  arquitectura: "🏛️",
  "asesor financiero": "💶",
  audiología: "👂",
  auditoría: "📊",
  autoescuela: "🚙",
  "banco-sucursal": "🏦",
  bar: "🍺",
  barbería: "💈",
  bodega: "🍷",
  "bolsos-complementos": "👜",
  boutique: "👗",
  "bróker hipotecario": "📉",
  "bufete de abogados": "⚖️",
  cafetería: "☕",
  calefacción: "🔥",
  "call center-bpo": "🎧",
  calzado: "👟",
  camping: "🏕️",
  carnicería: "🥩",
  carpintería: "🪚",
  "casa rural": "🏡",
  catering: "🥗",
  cementerio: "🪦",
  "centro cultural": "🏛️",
  "centro de estética": "💅",
  cerrajería: "🔑",
  "chapa-pintura": "🛠️",
  cine: "🎬",
  "climatización-a/c": "❄️",
  "clínica dental": "🦷",
  "clínica veterinaria": "🐾",
  "compra-venta de vehículos": "🚗",
  concesionario: "🚙",
  constructora: "🏗️",
  "consulta médica": "🩺",
  consultoría: "💼",
  "control de plagas": "🐜",
  "cooperativa de crédito": "💳",
  "correduría de seguros": "🛡️",
  coworking: "🏢",
  cristalería: "🪟",
  "cómics-juegos": "🎲",
  delicatessen: "🍇",
  dentista: "🦷",
  "depilación láser": "🔦",
  deportes: "⚽",
  discoteca: "💃",
  "diseño gráfico-branding": "🎨",
  domótica: "🏠",
  electricidad: "💡",
  "electrónica-telefonía (retail)": "📱",
  "energías renovables": "🌞",
  "escape room": "🧩",
  "escuela de artes": "🎭",
  ferretería: "🔩",
  "financiación-préstamos": "💰",
  fisioterapia: "🧘‍♂️",
  fontanería: "🚰",
  "food truck": "🚚",
  "fotografía-estudio": "📸",
  frutería: "🍎",
  funeraria: "⚰️",
  "galería de arte": "🖼️",
  "gasolinera-estación de servicio": "⛽",
  "gestoría-asesoría fiscal": "🧾",
  "guardería-residencia": "🏡",
  "guía turístico": "🗺️",
  heladería: "🍦",
  hipermercado: "🏬",
  "hospital veterinario": "🏥",
  "hostal-pensión": "🏨",
  hotel: "🏨",
  "imprenta-copistería": "🖨️",
  "informática (retail)": "💻",
  ingeniería: "🧰",
  inmobiliaria: "🏘️",
  "insumos agrícolas": "🌾",
  joyería: "💍",
  juguetería: "🧸",
  "lavado de coches": "🧽",
  lavandería: "🧺",
  lencería: "👙",
  librería: "📚",
  "logística-almacén": "📦",
  "medicina estética": "💉",
  "mensajería-paquetería": "📦",
  mercería: "🧵",
  microblading: "👁️",
  museo: "🏛️",
  "música-instrumentos": "🎸",
  neumáticos: "🛞",
  notaría: "✒️",
  "nutrición-dietética": "🥦",
  "náutica-astillero": "⛵",
  "oficina de turismo": "🧭",
  ortodoncia: "😁",
  outlet: "💸",
  "panadería-pastelería": "🥐",
  papelería: "📎",
  "parque de ocio": "🎡",
  peluquería: "💇‍♀️",
  "peluquería canina": "🐶",
  pescadería: "🐟",
  piercing: "💎",
  pilates: "🧍‍♀️",
  pintura: "🎨",
  podología: "🦶",
  procurador: "📜",
  "protección de datos-compliance": "🔒",
  psicología: "🧠",
  psiquiatría: "💊",
  pub: "🍻",
  "puerto deportivo": "🚤",
  "reformas integrales": "🏗️",
  rehabilitación: "🦿",
  relojería: "⌚",
  restaurante: "🍽️",
  "sala de conciertos": "🎵",
  "sala de juegos": "🎮",
  "salón de uñas": "💅",
  "sastrería-arreglos": "🧵",
  serigrafía: "👕",
  solárium: "🌞",
  "spa-balneario": "💧",
  "suelos-parquet": "🪵",
  supermercado: "🛒",
  "taller de bicicletas": "🚲",
  "taller de motos": "🏍️",
  "taller mecánico": "🛠️",
  tanatorio: "🕯️",
  "tasación-valoración": "📈",
  tatuajes: "🖋️",
  teatro: "🎭",
  "tienda de mascotas": "🐕",
  "tienda de ropa": "👗",
  "tienda gourmet": "🧀",
  tintorería: "👔",
  "toldos-persianas": "🏘️",
  touroperador: "🚌",
  "traducción-interpretación": "🗣️",
  "transporte de mercancías": "🚚",
  ultramarinos: "🥫",
  yoga: "🧘‍♀️",
  "óptica": "👓",
};

// Helper: normaliza a minúsculas y aplica fallback
export function getBusinessIcon(type: string): string {
  if (!type) return "🏠";
  const key = type.trim().toLowerCase();
  return BUSINESS_TYPE_ICONS[key] ?? "🏠";
}
